import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: 'lightgray',
          padding: '10px',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
        >
          <h1>Header</h1>
        </header>
        {children}
        <footer style={{
          backgroundColor: 'lightgray',
          padding: '10px',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
        >
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}
